<?php

if (!defined('BASEPATH'))exit('No direct script access allowed');



/* */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-09 16:17:54 */
/* http://harviacode.com */

 class Jadwal_service_model extends CI_Model{
  var $table = 'tb_jadwal';
  var $id    = 'id_jadwal';

    // datatables
      function json() {
          $this->datatables->select('tb_jadwal.id_jadwal,
                                      tb_jadwal.id_trans_kendaraan,
                                      DATE_FORMAT(tb_jadwal.waktu, "%d/%m/%Y %h:%s") AS waktu,
                                      tb_jadwal.keterangan,
                                      trans_kendaraan.id_pemilik,
                                      trans_kendaraan.aktif,
                                      tb_pemilik.id_pemilik,
                                      tb_pemilik.nama_pemilik,
                                      trans_kendaraan.no_registrasi
                                    ');
          $this->datatables->from('tb_jadwal');
          $this->datatables->join('trans_kendaraan', 'trans_kendaraan.id_trans_kendaraan = tb_jadwal.id_trans_kendaraan');
          $this->datatables->join('tb_pemilik', 'trans_kendaraan.id_pemilik = tb_pemilik.id_pemilik');
          $this->datatables->where('trans_kendaraan.aktif','y');
          $this->datatables->add_column('action',
          '<a href="'.site_url(config_item("cpanel")."jadwal_service/detail/$1").'" id="detail" data-toggle="tooltip" data-placement="top" title="Detail" class="text-primary"><i class="fa fa-file"></i></a>&nbsp;
           <a href="'.site_url(config_item("cpanel")."jadwal_service/hapus/$1").'" id="hapus" data-toggle="tooltip" data-placement="top" title="Hapus" class="text-danger "><i class="fa fa-trash"></i></a>',
           'id_jadwal');
          return $this->datatables->generate();
      }


     function get_data()
      {
        return $this->db->query("SELECT * FROM $this->table ORDER BY $this->id DESC");
      }


      function get_insert($data)
        {
          return $this->db->insert($this->table,$data);
        }


      function get_where($where)
        {
          return $this->db->query("SELECT
                                      tb_jadwal.id_jadwal,
                                      tb_jadwal.id_trans_kendaraan,
                                      tb_jadwal.waktu,
                                      tb_jadwal.keterangan,
                                      trans_kendaraan.id_pemilik,
                                      trans_kendaraan.aktif,
                                      tb_pemilik.id_pemilik,
                                      tb_pemilik.nama_pemilik,
                                      trans_kendaraan.no_registrasi
                                    FROM
                                      tb_jadwal
                                    INNER JOIN trans_kendaraan ON
                                      trans_kendaraan.id_trans_kendaraan = tb_jadwal.id_trans_kendaraan
                                    INNER JOIN tb_pemilik ON
                                      trans_kendaraan.id_pemilik = tb_pemilik.id_pemilik
                                    WHERE
                                      tb_jadwal.id_jadwal = $where
                                    ")
                          ->row();
        }


      function get_update($where,$data)
        {
          return $this->db
                ->where($this->id,$where)
                ->update($this->table,$data);
        }


      function get_delete($where)
        {
          return $this->db->where($this->id,$where)
                          ->delete($this->table);
        }

}
  /* End Model */
