<?php

if (!defined('BASEPATH'))exit('No direct script access allowed');



/* */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-15 01:22:24 */
/* http://harviacode.com */

 class Jenis_perbaikan_model extends CI_Model{
  var $table = 'tb_jenis_perbaikan';
  var $id    = 'id_jenis_perbaikan';

    // datatables
      function json() {
          $this->datatables->select('id_jenis_perbaikan,jenis_perbaikan');
          $this->datatables->from('tb_jenis_perbaikan');
          //add this line for join
          //$this->datatables->join('table2', 'tb_jenis_perbaikan.field = table2.field');
          $this->datatables->add_column('action',
          '
           <a href="'.site_url(config_item("cpanel")."jenis_perbaikan/edit/$1").'" id="edit" data-toggle="tooltip" data-placement="top" title="Edit" class="text-warning "><i class="fa fa-pencil"></i></a>&nbsp;
           <a href="'.site_url(config_item("cpanel")."jenis_perbaikan/hapus/$1").'" id="hapus" data-toggle="tooltip" data-placement="top" title="Hapus" class="text-danger "><i class="fa fa-trash"></i></a>',
           'id_jenis_perbaikan');
          return $this->datatables->generate();
      }


     function get_data()
      {
        return $this->db->query("SELECT * FROM $this->table ORDER BY $this->id DESC");
      }


      function get_insert($data)
        {
          return $this->db->insert($this->table,$data);
        }


      function get_where($where)
        {
          return $this->db->where($this->id,$where)
                          ->get($this->table)
                          ->row();
        }


      function get_update($where,$data)
        {
          return $this->db
                ->where($this->id,$where)
                ->update($this->table,$data);
        }


      function get_delete($where)
        {
          $query = $this->db->where($this->id,$where)
                          ->delete($this->table);

        if (!$query) {
            return false;
          }else {
            return true;
          }
        }

}
  /* End Model */
