<?php

if (!defined('BASEPATH'))exit('No direct script access allowed');



/* */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-01-03 20:09:03 */
/* http://harviacode.com */

 class Notifikasi_cs_model extends CI_Model{
  var $table = 'tb_notifikasi_cs';
  var $id    = 'id_notif';

    // datatables
      function json() {
          $this->datatables->select('tb_notifikasi_cs.id_notif,
                                    tb_notifikasi_cs.id_trans_kendaraan,
                                    tb_notifikasi_cs.notifikasi,
                                    DATE_FORMAT(tb_notifikasi_cs.waktu, "%d/%m/%Y") AS waktu,
                                    tb_notifikasi_cs.status,
                                    trans_kendaraan.no_registrasi,
                                    tb_pemilik.nama_pemilik,
                                    trans_kendaraan.aktif');
          $this->datatables->from('tb_notifikasi_cs');
          //add this line for join
          $this->datatables->join('trans_kendaraan', 'tb_notifikasi_cs.id_trans_kendaraan = trans_kendaraan.id_trans_kendaraan');
          $this->datatables->join('tb_pemilik', 'trans_kendaraan.id_pemilik = tb_pemilik.id_pemilik');
          $this->datatables->where('trans_kendaraan.aktif','y');
          $this->datatables->add_column('action',
          '<a href="'.site_url(config_item("cpanel")."notifikasi_cs/detail/$1").'" id="detail" data-toggle="tooltip" data-placement="top" title="Detail" class="text-primary"><i class="fa fa-file"></i></a>&nbsp;

           <a href="'.site_url(config_item("cpanel")."notifikasi_cs/hapus/$1").'" id="hapus" data-toggle="tooltip" data-placement="top" title="Hapus" class="text-danger "><i class="fa fa-trash"></i></a>',
           'id_notif');
          return $this->datatables->generate();

          // <a href="'.site_url(config_item("cpanel")."notifikasi_cs/edit/$1").'" id="edit" data-toggle="tooltip" data-placement="top" title="Edit" class="text-warning "><i class="fa fa-pencil"></i></a>&nbsp;
      }

      function get_detail($id)
      {
        return $this->db->select('tb_notifikasi_cs.id_notif,
                                  tb_notifikasi_cs.id_trans_kendaraan,
                                  tb_notifikasi_cs.notifikasi,
                                  DATE_FORMAT(tb_notifikasi_cs.waktu, "%d/%m/%Y") AS waktu,
                                  tb_notifikasi_cs.status,
                                  trans_kendaraan.no_registrasi,
                                  tb_pemilik.nama_pemilik,
                                  trans_kendaraan.aktif')
                        ->from('tb_notifikasi_cs')
                        //add this line for join
                        ->join('trans_kendaraan', 'tb_notifikasi_cs.id_trans_kendaraan = trans_kendaraan.id_trans_kendaraan')
                        ->join('tb_pemilik', 'trans_kendaraan.id_pemilik = tb_pemilik.id_pemilik')
                        ->where('tb_notifikasi_cs.id_notif',$id)
                        ->where('trans_kendaraan.aktif','y')
                        ->get();
      }


     function get_data()
      {
        return $this->db->query("SELECT * FROM $this->table ORDER BY $this->id DESC");
      }


      function get_insert($data)
        {
          return $this->db->insert($this->table,$data);
        }


      function get_where($where)
        {
          return $this->db->where($this->id,$where)
                          ->get($this->table)
                          ->row();
        }


      function get_update($where,$data)
        {
          return $this->db
                ->where($this->id,$where)
                ->update($this->table,$data);
        }


      function get_delete($where)
        {
          return $this->db->where($this->id,$where)
                          ->delete($this->table);
        }

}
  /* End Model */
