<?php

if (!defined('BASEPATH'))exit('No direct script access allowed');



/* */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-17 23:43:45 */
/* http://harviacode.com */

 class Profile_model extends CI_Model{
  var $table = 'tb_profile';
  var $id    = 'id_profile';

    // datatables
      function json() {
          $this->datatables->select('id_profile,nama_bengkel,email,telepon,alamat,kordinat');
          $this->datatables->from('tb_profile');
          //add this line for join
          //$this->datatables->join('table2', 'tb_profile.field = table2.field');
          $this->datatables->add_column('action',
          '<a href="'.site_url(config_item("cpanel")."profile/detail/$1").'" id="detail" data-toggle="tooltip" data-placement="top" title="Detail" class="text-primary"><i class="fa fa-file"></i></a>&nbsp;
           <a href="'.site_url(config_item("cpanel")."profile/edit/$1").'" id="edit" data-toggle="tooltip" data-placement="top" title="Edit" class="text-warning "><i class="fa fa-pencil"></i></a>&nbsp;
           <a href="'.site_url(config_item("cpanel")."profile/hapus/$1").'" id="hapus" data-toggle="tooltip" data-placement="top" title="Hapus" class="text-danger "><i class="fa fa-trash"></i></a>',
           'id_profile');
          return $this->datatables->generate();
      }


     function get_data()
      {
        return $this->db->query("SELECT * FROM $this->table ORDER BY $this->id DESC");
      }


      function get_insert($data)
        {
          return $this->db->insert($this->table,$data);
        }


      function get_where($where)
        {
          return $this->db->where($this->id,$where)
                          ->get($this->table)
                          ->row();
        }


      function get_update($where,$data)
        {
          return $this->db
                ->where($this->id,$where)
                ->update($this->table,$data);
        }


      function get_delete($where)
        {
          return $this->db->where($this->id,$where)
                          ->delete($this->table);
        }

}
  /* End Model */
  