<?php

if (!defined('BASEPATH'))exit('No direct script access allowed');



/* */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-16 22:28:02 */
/* http://harviacode.com */

 class Service_model extends CI_Model{
  var $table = 'tb_service';
  var $id    = 'id_service';

    // datatables
      function json() {
          $this->datatables->select('id_service,nama_service,jarak_tempuh,waktu');
          $this->datatables->from('tb_service');
          //add this line for join
          //$this->datatables->join('table2', 'tb_service.field = table2.field');
          $this->datatables->add_column('action',
          '<a href="'.site_url(config_item("cpanel")."service/detail/$1").'" id="detail" data-toggle="tooltip" data-placement="top" title="Detail" class="text-primary"><i class="fa fa-file"></i></a>&nbsp;
           <a href="'.site_url(config_item("cpanel")."service/edit/$1").'" id="edit" data-toggle="tooltip" data-placement="top" title="Edit" class="text-warning "><i class="fa fa-pencil"></i></a>&nbsp;
           <a href="'.site_url(config_item("cpanel")."service/hapus/$1").'" id="hapus" data-toggle="tooltip" data-placement="top" title="Hapus" class="text-danger "><i class="fa fa-trash"></i></a>',
           'id_service');
          return $this->datatables->generate();
      }

      function join_trans_service($where)
      {
        return $this->db->query("SELECT
                                  trans_service.id_trans_service,
                                  trans_service.id_service,
                                  trans_service.id_perbaikan,
                                  tb_jenis_perbaikan.jenis_perbaikan
                                  FROM
                                  trans_service
                                  INNER JOIN tb_jenis_perbaikan ON tb_jenis_perbaikan.id_jenis_perbaikan = trans_service.id_perbaikan
                                  WHERE
                                  trans_service.id_service = $where"
                                )
                          ->result();
      }

     function get_data()
      {
        return $this->db->query("SELECT * FROM $this->table ORDER BY $this->id DESC");
      }


      function get_insert($table,$data)
        {
          return $this->db->insert($table,$data);
        }


      function get_where($where)
        {
          return $this->db->where($this->id,$where)
                          ->get($this->table)
                          ->row();
        }


      function get_update($where,$data)
        {
          return $this->db
                ->where($this->id,$where)
                ->update($this->table,$data);
        }


      function get_delete($table,$where)
        {
          $query = $this->db->where($where)
                          ->delete($table);
          if (!$query) {
              return false;
            }else {
              return true;
            }
        }

}
  /* End Model */
