<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Customer.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Customer.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-09 18:18:36 */
/* http://harviacode.com */

 class Customer extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->_security_admin("backend");
      $this->load->library(array("Layouts"));
      $this->load->model('Customer_model','model');
      $this->load->helper('backend');
  }

 function _rules(){
		$this->form_validation->set_rules('nama_pemilik', 'Nama', 'trim|xss_clean|required');
		$this->form_validation->set_rules('telepon_pemilik', 'Telepon', 'trim|xss_clean|required');
		$this->form_validation->set_rules('email_pemilik', 'Email', 'trim|xss_clean|required');
		$this->form_validation->set_rules('alamat_pemilik', 'Alamat', 'trim|xss_clean|required');
		$this->form_validation->set_rules('jk_pemilik', 'Jenis Kelamin', 'trim|xss_clean|required');
		// $this->form_validation->set_rules('foto_pemilik', 'Foto', 'trim|xss_clean|required');

    $this->form_validation->set_rules('no_kendaraan', 'No.Kendaraan', 'trim|xss_clean|required|alpha_numeric');
    $this->form_validation->set_rules('merek_kendaraan', 'Merek', 'trim|xss_clean|required');
    $this->form_validation->set_rules('transmisi_kendaraan', 'Transmisi', 'trim|xss_clean|required');
    $this->form_validation->set_rules('cc_kendaraan', 'Kapasitas Mesin', 'trim|xss_clean|required|numeric');
    $this->form_validation->set_rules('warna_kendaraan', 'Warna', 'trim|xss_clean|required');
    $this->form_validation->set_rules('tahun_pembuatan', 'Tahun Pembuatan', 'trim|xss_clean|required|numeric');
    $this->form_validation->set_rules('kilometer', 'Kilometer Sekarang', 'trim|xss_clean|required|numeric');
    $this->form_validation->set_rules('waktu_pembelian', 'Tahun Pembelian', 'trim|xss_clean|required');


		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Customer');
    $this->layouts->view(config_item("cpanel").'content/customer/index');
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


 function detail($id){
    if($row=$this->model->get_data_join($id)){
      $this->layouts->set_title('Customer');
        $data=array('layout_title' => 'Customer',
                    'id_trans_kendaraan'=>$id,
										'id_pemilik' => $row->id_pemilik,
										'nama_pemilik' => $row->nama_pemilik,
										'telepon_pemilik' => $row->telepon_pemilik,
										'email_pemilik' => $row->email_pemilik,
										'alamat_pemilik' => $row->alamat_pemilik,
										'jk_pemilik' => $row->jk_pemilik,
										'foto_pemilik' => $row->foto_pemilik,
                    'no_registrasi' => $row->no_registrasi,
                    'tgl_registrasi' => $row->tgl_registrasi,
                    'no_kendaraan' => $row->no_kendaraan,
                    'merek_kendaraan' => $row->merek_kendaraan,
                    'transmisi_kendaraan' => $row->transmisi_kendaraan,
                    'cc_kendaraan' => $row->cc_kendaraan,
                    'warna_kendaraan' => $row->warna_kendaraan,
                    'tahun_pembuatan' => $row->tahun_pembuatan,
                    'waktu_pembelian' => $row->waktu_pembelian,
                    'kilometer' => $row->kilometer,
									);
				 $this->layouts->view(config_item("cpanel").'content/customer/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view(config_item("cpanel").'content/customer/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

  function detail_service($id_trans_kendaraan,$id_service){
     if($row=$this->model->get_where_join_detail_service($id_trans_kendaraan,$id_service)){
       $this->layouts->set_title("Tahap $row->nama_service");
         $data=array('layout_title' => "Tahap $row->nama_service",
 										'id_trans_cs_service' => $row->id_trans_cs_service,
 										'id_trans_kendaraan' => $row->id_trans_kendaraan,
 										'id_service' => $row->id_service,
 										'keterangan' => $row->keterangan,
 										'waktu_service' => $row->waktu_service,
                     'nama_pemilik'=>$row->nama_pemilik,
                     'no_registrasi'=>$row->no_registrasi,
                     'jarak_tempuh'=>$row->jarak_tempuh,
                     'waktu_tempuh'=>$row->waktu_tempuh,
                     'nama_service'=>$row->nama_service
 									);
 				 $this->layouts->view(config_item("cpanel").'content/cs_service/detail',array(),$data);
 //MODAL DETAIL
 //$this->layouts->view(config_item("cpanel").'content/cs_service/detail',array(),$data,false);
     }else {
         $this->error_404();
     }
   }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
          if(isset($_FILES['userfile']['name']) && $_FILES['userfile']['name']!=""){
              $file_name = substr($_FILES['userfile']['name'],-4);
              $image_name = $this->input->post('userfile',true)."".$file_name;
            }else {
              $image_name = null;
            }
            $this->form_validation->set_rules('userfile', 'Foto', 'trim|xss_clean|callback__cekfile['.$image_name.']');
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'nama_pemilik' => $this->input->post('nama_pemilik',TRUE),
																'telepon_pemilik' => $this->input->post('telepon_pemilik',TRUE),
																'email_pemilik' => $this->input->post('email_pemilik',TRUE),
																'alamat_pemilik' => $this->input->post('alamat_pemilik',TRUE),
																'jk_pemilik' => $this->input->post('jk_pemilik',TRUE),
																'foto_pemilik' => $image_name,
															);
                  $this->model->get_insert("tb_pemilik",$insert);
                  $id_pemilik = $this->db->insert_id();
                  $insert_kendaraan = array('no_kendaraan' => $this->input->post('no_kendaraan',TRUE),
                                            'merek_kendaraan' => $this->input->post('merek_kendaraan',TRUE),
                                            'transmisi_kendaraan' => $this->input->post('transmisi_kendaraan',TRUE),
                                            'cc_kendaraan' => $this->input->post('cc_kendaraan',TRUE),
                                            'warna_kendaraan' => $this->input->post('warna_kendaraan',TRUE),
                                            'tahun_pembuatan' => $this->input->post('tahun_pembuatan',TRUE),
                                            'waktu_pembelian' => date('Y-m-d',strtotime($this->input->post('waktu_pembelian',TRUE))),
                                            'kilometer' => $this->input->post('kilometer',TRUE),
                                            'kilometer_skrg' => $this->input->post('kilometer',TRUE),
                                          );
                $this->model->get_insert("tb_kendaraan",$insert_kendaraan);
                $id_kendaraan = $this->db->insert_id();
                $trans = array( 'no_registrasi'=>date('dmyhis'),
                                'tgl_registrasi'=>date('Y-m-d'),
                                'id_pemilik' => $id_pemilik,
                                'id_kendaraan' => $id_kendaraan
                              );
                $this->model->get_insert("trans_kendaraan",$trans);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Customer');
      $data = array('layout_title' => 'Customer',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'customer/tambah/aksi'),
											'nama_pemilik' => set_value('nama_pemilik'),
											'telepon_pemilik' => set_value('telepon_pemilik'),
											'email_pemilik' => set_value('email_pemilik'),
											'alamat_pemilik' => set_value('alamat_pemilik'),
											'jk_pemilik' => set_value('jk_pemilik'),
											'userfile' => set_value('userfile','customer_'.date('dmYhis')),

                      'no_kendaraan' => set_value('no_kendaraan'),
                      'merek_kendaraan' => set_value('merek_kendaraan'),
                      'transmisi_kendaraan' => set_value('transmisi_kendaraan'),
                      'cc_kendaraan' => set_value('cc_kendaraan'),
                      'warna_kendaraan' => set_value('warna_kendaraan'),
                      'tahun_pembuatan' => set_value('tahun_pembuatan'),
                      'waktu_pembelian' => set_value('waktu_pembelian'),
                      'kilometer' => set_value('kilometer'),
											);
			 $this->layouts->view(config_item("cpanel").'content/customer/form',array(),$data);
  //MODAL TAMBAH
  //$this->layouts->view(config_item("cpanel").'content/customer/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
            if(isset($_FILES['userfile']['name']) && $_FILES['userfile']['name']!=""){
                if ($this->input->post('userfile',true)=="") {
                  $file_name = substr($_FILES['userfile']['name'],-4);
                  $image_name = "customer_".date('dmYhis')."".$file_name;
                }else {
                  $image_name = $this->input->post('userfile',true);
                }
              }else {
                $image_name = $this->input->post('userfile',true);
              }
                $this->form_validation->set_rules('userfile', 'Foto', 'trim|xss_clean|callback__cekfile['.$image_name.']');
                $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'nama_pemilik' => $this->input->post('nama_pemilik',TRUE),
																'telepon_pemilik' => $this->input->post('telepon_pemilik',TRUE),
																'email_pemilik' => $this->input->post('email_pemilik',TRUE),
																'alamat_pemilik' => $this->input->post('alamat_pemilik',TRUE),
																'jk_pemilik' => $this->input->post('jk_pemilik',TRUE),
																'foto_pemilik' => $image_name,
															);
                $this->model->get_update('tb_pemilik',array('id_pemilik'=>$this->input->post('id_pemilik',TRUE)),$update);

                $update_kendaraan = array('no_kendaraan' => $this->input->post('no_kendaraan',TRUE),
                                          'merek_kendaraan' => $this->input->post('merek_kendaraan',TRUE),
                                          'transmisi_kendaraan' => $this->input->post('transmisi_kendaraan',TRUE),
                                          'cc_kendaraan' => $this->input->post('cc_kendaraan',TRUE),
                                          'warna_kendaraan' => $this->input->post('warna_kendaraan',TRUE),
                                          'tahun_pembuatan' => $this->input->post('tahun_pembuatan',TRUE),
                                          'waktu_pembelian' => date('Y-m-d',strtotime($this->input->post('waktu_pembelian',TRUE))),
                                          'kilometer' => $this->input->post('kilometer',TRUE),
                                          'kilometer_skrg' => $this->input->post('kilometer',TRUE),
                                        );
                $this->model->get_update('tb_kendaraan',array('id_kendaraan'=>$this->input->post('id_kendaraan',TRUE)),$update_kendaraan);

                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_data_join($id)){
        $this->layouts->set_title('Customer');
        $data = array('layout_title' => 'Customer',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'customer/edit/'.$id.'/aksi'),
                      'id_pemilik' => set_value('id_pemilik', $row->id_pemilik),
											'nama_pemilik' => set_value('nama_pemilik', $row->nama_pemilik),
											'telepon_pemilik' => set_value('telepon_pemilik', $row->telepon_pemilik),
											'email_pemilik' => set_value('email_pemilik', $row->email_pemilik),
											'alamat_pemilik' => set_value('alamat_pemilik', $row->alamat_pemilik),
											'jk_pemilik' => set_value('jk_pemilik', $row->jk_pemilik),
											'userfile' => set_value('userfile', $row->foto_pemilik),
                      'id_kendaraan' => set_value('id_kendaraan',$row->id_kendaraan),
                      'no_kendaraan' => set_value('no_kendaraan',$row->no_kendaraan),
                      'merek_kendaraan' => set_value('merek_kendaraan',$row->merek_kendaraan),
                      'transmisi_kendaraan' => set_value('transmisi_kendaraan',$row->transmisi_kendaraan),
                      'cc_kendaraan' => set_value('cc_kendaraan',$row->cc_kendaraan),
                      'warna_kendaraan' => set_value('warna_kendaraan',$row->warna_kendaraan),
                      'tahun_pembuatan' => set_value('tahun_pembuatan',$row->tahun_pembuatan),
                      'waktu_pembelian' => set_value('waktu_pembelian',$row->waktu_pembelian),
                      'kilometer' => set_value('kilometer',$row->kilometer),
											);
			 $this->layouts->view(config_item("cpanel").'content/customer/form',array(),$data);
  //MODAL EDIT
  //$this->layouts->view(config_item("cpanel").'content/customer/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
      $this->model->get_update("trans_kendaraan",array("id_trans_kendaraan"=>$id),array('aktif'=>'n'));
      $data['alert'] = 'Berhasil menghapus!';
      echo json_encode($data);
    }
}


function cek_service($id)
{

$qry_kendaraan =  $this->db->query("SELECT
                                    trans_kendaraan.id_trans_kendaraan,
                                    trans_kendaraan.tgl_registrasi,
                                    trans_kendaraan.aktif,
                                    trans_kendaraan.id_kendaraan,
                                    tb_kendaraan.kilometer,
                                    tb_kendaraan.kilometer_skrg
                                    FROM
                                    trans_kendaraan
                                    INNER JOIN tb_kendaraan ON trans_kendaraan.id_kendaraan = tb_kendaraan.id_kendaraan
                                    WHERE
                                    trans_kendaraan.id_trans_kendaraan=$id AND trans_kendaraan.aktif = 'y'
                                    ");

    if ($qry_kendaraan->num_rows() > 0) {
      $qr = $qry_kendaraan->row();
      $jarak = ($qr->kilometer_skrg - $qr->kilometer);
      $waktu = selisih_bulan($qr->tgl_registrasi);


      $service = $this->db->query('SELECT * FROM tb_service WHERE '.$jarak.' >= jarak_tempuh AND '.$jarak.' < s_jarak_tempuh OR '.$waktu.' >= waktu AND '.$waktu.' < s_waktu')->row();

      $cek_service = $this->db->query("SELECT * FROM trans_cs_service WHERE id_trans_kendaraan=$id AND id_service=$service->id_service");

      if ($cek_service->num_rows()>0) {
        $val = '<b class="text-success"><i class="fa fa-check"></i> '.$service->nama_service.'</b>';
      }else {
        $val = '<b class="text-danger"><i class="fa fa-close"></i> '.$service->nama_service.'</b>';
      }
      $data['success'] = true;
      $data['hsl'] = $val;
    }else {
      $data['hsl'] = "null";
    }



  $this->output
        ->set_content_type('application/json')
        ->set_output(json_encode($data));
}

}
/* End Controller */
