<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Jadwal_service.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Jadwal_service.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-08-09 16:17:54 */
/* http://harviacode.com */

 class Jadwal_service extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->_security_admin("backend");
      $this->load->library(array("Layouts"));
      $this->load->model('Jadwal_service_model','model');
      $this->load->helper('backend');
  }

 function _rules(){
		$this->form_validation->set_rules('id_trans_kendaraan', 'id trans kendaraan', 'trim|xss_clean|required');
		$this->form_validation->set_rules('tanggal', 'Tanggal', 'trim|xss_clean|required');
    $this->form_validation->set_rules('jam', 'Jam', 'trim|xss_clean|required');
		$this->form_validation->set_rules('keterangan', 'keterangan', 'trim|xss_clean|required');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Jadwal Service');
    $this->layouts->view(config_item("cpanel").'content/jadwal_service/index');
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


 function detail($id){
    if($row=$this->model->get_where($id)){
      $this->layouts->set_title('Jadwal Service');
        $data=array('layout_title' => 'Jadwal Service',
										'id_jadwal' => $row->id_jadwal,
										'id_trans_kendaraan' => $row->id_trans_kendaraan,
                    'nama'  => $row->nama_pemilik,
                    'no_registrasi'  => $row->no_registrasi,
										'waktu' => $row->waktu,
										'keterangan' => $row->keterangan,
									);
				 $this->layouts->view(config_item("cpanel").'content/jadwal_service/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view(config_item("cpanel").'content/jadwal_service/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($id,$status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->_rules();
            $tanggal = $this->input->post('tanggal',TRUE);
            $jam = $this->input->post('jam',TRUE);
            $waktu = $tanggal." ".$jam;
            if ($this->form_validation->run()) {
                $insert = array(
																'id_trans_kendaraan' => $this->input->post('id_trans_kendaraan',TRUE),
																'waktu' => $waktu,
																'keterangan' => $this->input->post('keterangan',TRUE),
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Jadwal Service');
      $data = array('layout_title' => 'Jadwal Service',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'jadwal_service/tambah/'.$id.'/aksi'),
											'id_jadwal' => set_value('id_jadwal'),
											'id_trans_kendaraan' => set_value('id_trans_kendaraan',$id),
											'tanggal' => set_value('tanggal'),
                      'jam' => set_value('jam'),
											'keterangan' => set_value('keterangan'),
											);
			 $this->layouts->view(config_item("cpanel").'content/jadwal_service/form',array(),$data,false);
  //MODAL TAMBAH
  //$this->layouts->view(config_item("cpanel").'content/jadwal_service/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              $tanggal = $this->input->post('tanggal',TRUE);
              $jam = $this->input->post('jam',TRUE);
              $waktu = $tanggal." ".$jam;
              if ($this->form_validation->run()) {
                  $update = array(
																'id_trans_kendaraan' => $this->input->post('id_trans_kendaraan',TRUE),
																'waktu' => date('Y-m-d h:i:s', strtotime($waktu)),
																'keterangan' => $this->input->post('keterangan',TRUE),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Jadwal Service');
        $data = array('layout_title' => 'Jadwal Service',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'jadwal_service/edit/'.$id.'/aksi'),
											'id_jadwal' => set_value('id_jadwal', $row->id_jadwal),
											'id_trans_kendaraan' => set_value('id_trans_kendaraan', $row->id_trans_kendaraan),
											'waktu' => set_value('waktu', $row->waktu),
											'keterangan' => set_value('keterangan', $row->keterangan),
											);
			 $this->layouts->view(config_item("cpanel").'content/jadwal_service/form',array(),$data);
  //MODAL EDIT
  //$this->layouts->view(config_item("cpanel").'content/jadwal_service/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
      $this->model->get_delete($id);
      $data['alert'] = 'Berhasil menghapus!';
      echo json_encode($data);
    }
}

}
/* End Controller */
