<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Jenis_perbaikan.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Jenis_perbaikan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-15 01:22:24 */
/* http://harviacode.com */

 class Jenis_perbaikan extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->_security_admin("backend");
      $this->load->library(array("Layouts"));
      $this->load->model('Jenis_perbaikan_model','model');
      $this->load->helper('backend');
  }

 function _rules(){
		$this->form_validation->set_rules('jenis_perbaikan', 'jenis perbaikan', 'trim|xss_clean|required');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Jenis Perbaikan');
    $this->layouts->view(config_item("cpanel").'content/jenis_perbaikan/index');
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


 function detail($id){
    if($row=$this->model->get_where($id)){
      $this->layouts->set_title('Jenis Perbaikan');
        $data=array('layout_title' => 'Jenis Perbaikan',
										'id_jenis_perbaikan' => $row->id_jenis_perbaikan,
										'jenis_perbaikan' => $row->jenis_perbaikan,
									);
				 $this->layouts->view(config_item("cpanel").'content/jenis_perbaikan/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view(config_item("cpanel").'content/jenis_perbaikan/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'jenis_perbaikan' => $this->input->post('jenis_perbaikan',TRUE),
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Jenis Perbaikan');
      $data = array('layout_title' => 'Jenis Perbaikan',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'jenis_perbaikan/tambah/aksi'),
											'id_jenis_perbaikan' => set_value('id_jenis_perbaikan'),
											'jenis_perbaikan' => set_value('jenis_perbaikan'),
											);
			 // $this->layouts->view(config_item("cpanel").'content/jenis_perbaikan/form',array(),$data);
  //MODAL TAMBAH
  $this->layouts->view(config_item("cpanel").'content/jenis_perbaikan/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'jenis_perbaikan' => $this->input->post('jenis_perbaikan',TRUE),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Jenis Perbaikan');
        $data = array('layout_title' => 'Jenis Perbaikan',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'jenis_perbaikan/edit/'.$id.'/aksi'),
											'id_jenis_perbaikan' => set_value('id_jenis_perbaikan', $row->id_jenis_perbaikan),
											'jenis_perbaikan' => set_value('jenis_perbaikan', $row->jenis_perbaikan),
											);
			 // $this->layouts->view(config_item("cpanel").'content/jenis_perbaikan/form',array(),$data);
  //MODAL EDIT
  $this->layouts->view(config_item("cpanel").'content/jenis_perbaikan/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
   if ($this->input->is_ajax_request()) {
     if ($this->model->get_delete($id)==false) {
       $data['alert'] = '<div id="alert" class="alert alert-danger">Gagal Menghapus, data ini terpakai di table lain!<div>';
     }else {
       $data['alert'] = '<div id="alert" class="alert alert-success">Berhasil Menghapus!<div>';
     }
       echo json_encode($data);
     }
}

}
/* End Controller */
