<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Notifikasi_cs.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Notifikasi_cs.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-01-03 20:09:03 */
/* http://harviacode.com */

 class Notifikasi_cs extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->_security_admin("backend");
      $this->load->library(array("Layouts"));
      $this->load->model('Notifikasi_cs_model','model');
      $this->load->helper('backend');
  }

 function _rules(){
		$this->form_validation->set_rules('notifikasi', 'notifikasi', 'trim|xss_clean|required');

		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Notifikasi Customer');
    $this->layouts->view(config_item("cpanel").'content/notifikasi_cs/index');
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


 function detail($id){
    if($row=$this->model->get_detail($id)->row()){
      $this->layouts->set_title('Notifikasi Customer');
        $data=array('layout_title' => 'Notifikasi Customer',
										'id_notif' => $row->id_notif,
										'id_trans_kendaraan' => $row->id_trans_kendaraan,
										'notifikasi' => $row->notifikasi,
										'waktu' => $row->waktu,
                    'no_registrasi' =>$row->no_registrasi,
                    'nama'=>$row->nama_pemilik
									);
				 $this->layouts->view(config_item("cpanel").'content/notifikasi_cs/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view(config_item("cpanel").'content/notifikasi_cs/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($id,$status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'id_trans_kendaraan' => $id,
																'notifikasi' => $this->input->post('notifikasi',TRUE),
																'waktu' => date('Y-m-d'),
																'status' => "belum",
															);
                $this->model->get_insert($insert);
                $json['alert']   = 'Berhasil mengirim notifikasi ke customer.';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Notifikasi Customer');
      $data = array('layout_title' => 'Notifikasi Customer',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'notifikasi_cs/tambah/'.$id.'/aksi'),
											'id_notif' => set_value('id_notif'),
											'id_trans_kendaraan' => set_value('id_trans_kendaraan'),
											'notifikasi' => set_value('notifikasi'),
											'waktu' => set_value('waktu'),
											'status' => set_value('status'),
											);
			 // $this->layouts->view(config_item("cpanel").'content/notifikasi_cs/form',array(),$data);
  //MODAL TAMBAH
  $this->layouts->view(config_item("cpanel").'content/notifikasi_cs/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'id_trans_kendaraan' => $this->input->post('id_trans_kendaraan',TRUE),
																'notifikasi' => $this->input->post('notifikasi',TRUE),
																'waktu' => $this->input->post('waktu',TRUE),
																'status' => $this->input->post('status',TRUE),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Notifikasi Customer');
        $data = array('layout_title' => 'Notifikasi Customer',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'notifikasi_cs/edit/'.$id.'/aksi'),
											'id_notif' => set_value('id_notif', $row->id_notif),
											'id_trans_kendaraan' => set_value('id_trans_kendaraan', $row->id_trans_kendaraan),
											'notifikasi' => set_value('notifikasi', $row->notifikasi),
											'waktu' => set_value('waktu', $row->waktu),
											'status' => set_value('status', $row->status),
											);
			 $this->layouts->view(config_item("cpanel").'content/notifikasi_cs/form',array(),$data);
  //MODAL EDIT
  //$this->layouts->view(config_item("cpanel").'content/notifikasi_cs/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
      $this->model->get_delete($id);
      $data['alert'] = 'Berhasil menghapus!';
      echo json_encode($data);
    }
}

}
/* End Controller */
