<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Profile.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Profile.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-17 23:43:45 */
/* http://harviacode.com */

 class Profile extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->_security_admin("backend");
      $this->load->library(array("Layouts"));
      $this->load->model('Profile_model','model');
      $this->load->helper('backend');
  }

 function _rules(){
		$this->form_validation->set_rules('nama_bengkel', 'nama bengkel', 'trim|xss_clean|required');
		$this->form_validation->set_rules('email', 'email', 'trim|xss_clean|required|valid_email');
		$this->form_validation->set_rules('telepon', 'telepon', 'trim|xss_clean|required|numeric');
		$this->form_validation->set_rules('alamat', 'alamat', 'trim|xss_clean|required');
		$this->form_validation->set_rules('kordinat', 'kordinat', 'trim|xss_clean|required');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
   if($row=$this->model->get_where(1)){
     $this->layouts->set_title('Profile');
       $data=array('layout_title' => 'Profile',
                   'id_profile' => $row->id_profile,
                   'nama_bengkel' => $row->nama_bengkel,
                   'email' => $row->email,
                   'telepon' => $row->telepon,
                   'alamat' => $row->alamat,
                   'kordinat' => $row->kordinat,
                 );
        $this->layouts->view(config_item("cpanel").'content/profile/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view(config_item("cpanel").'content/profile/detail',array(),$data,false);
   }else {
       $this->error_404();
   }
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


 function detail($id){
    if($row=$this->model->get_where($id)){
      $this->layouts->set_title('Profile');
        $data=array('layout_title' => 'Profile',
										'id_profile' => $row->id_profile,
										'nama_bengkel' => $row->nama_bengkel,
										'email' => $row->email,
										'telepon' => $row->telepon,
										'alamat' => $row->alamat,
										'kordinat' => $row->kordinat,
									);
				 $this->layouts->view(config_item("cpanel").'content/profile/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view(config_item("cpanel").'content/profile/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }


 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
              $this->_rules();
              if ($this->form_validation->run()) {
                  $update = array(
																'nama_bengkel' => $this->input->post('nama_bengkel',TRUE),
																'email' => $this->input->post('email',TRUE),
																'telepon' => $this->input->post('telepon',TRUE),
																'alamat' => $this->input->post('alamat',TRUE),
																'kordinat' => $this->input->post('kordinat',TRUE),
															);
                $this->model->get_update($id,$update);
                $json['alert']   = 'Berhasil Mengedit!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Profile');
        $data = array('layout_title' => 'Profile',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'profile/edit/'.$id.'/aksi'),
											'id_profile' => set_value('id_profile', $row->id_profile),
											'nama_bengkel' => set_value('nama_bengkel', $row->nama_bengkel),
											'email' => set_value('email', $row->email),
											'telepon' => set_value('telepon', $row->telepon),
											'alamat' => set_value('alamat', $row->alamat),
											'kordinat' => set_value('kordinat', $row->kordinat),
											);
			 $this->layouts->view(config_item("cpanel").'content/profile/form',array(),$data);
  //MODAL EDIT
  //$this->layouts->view(config_item("cpanel").'content/profile/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}


}
/* End Controller */
