<?php if (!defined('BASEPATH')) exit('No direct script access allowed');



/* Service.php */
/* HARVIACODE CRUD GENERATOR MVC/HMVC AJAX CRUD */
/* PENGEMBANG : MPAMPAM */
/* EMAIL : MPAMPAM5@GMAIL.COM */
/* FACEBOOK : https://www.facebook.com/mpampam */
/* Location: ./application/controllers/Service.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-11-16 22:28:02 */
/* http://harviacode.com */

 class Service extends MY_Controller{
  function __construct(){
      parent::__construct();
      $this->_security_admin("backend");
      $this->load->library(array("Layouts"));
      $this->load->model('Service_model','model');
      $this->load->helper('backend');
  }

 function _rules(){
		$this->form_validation->set_rules('nama_service', 'nama service', 'trim|xss_clean|required');
		$this->form_validation->set_rules('jarak_tempuh', 'jarak tempuh', 'trim|xss_clean|required|numeric');
		$this->form_validation->set_rules('waktu', 'waktu', 'trim|xss_clean|required|numeric');
    $this->form_validation->set_rules('check', 'Jenis Perbaikan', 'trim|xss_clean|required');
		$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
  }

 function index(){
    $this->layouts->set_title('Data Service');
    $this->layouts->view(config_item("cpanel").'content/service/index');
  }

function json() {
    header('Content-Type: application/json');
    echo $this->model->json();
}


 function detail($id){
    if($row=$this->model->get_where($id)){
      $this->layouts->set_title('Data Service');
        $data=array('layout_title' => 'Data Service',
										'id_service' => $row->id_service,
										'nama_service' => $row->nama_service,
										'jarak_tempuh' => $row->jarak_tempuh,
										'waktu' => $row->waktu,
                    'trans_service' => $this->model->join_trans_service($id),
									);
				 $this->layouts->view(config_item("cpanel").'content/service/detail',array(),$data);
//MODAL DETAIL
//$this->layouts->view(config_item("cpanel").'content/service/detail',array(),$data,false);
    }else {
        $this->error_404();
    }
  }

 function tambah($status=''){
    if ($status=='aksi') {
        $json = array('success'=>false ,'alert'=>array());
        if ($this->input->is_ajax_request()) {
            $this->form_validation->set_rules('s_jarak_tempuh', 'sampai jarak tempuh', 'trim|xss_clean|required|numeric|callback__s_jarak['.$this->input->post('jarak_tempuh',TRUE).']');
        		$this->form_validation->set_rules('s_waktu', 'sampai waktu', 'trim|xss_clean|required|numeric|callback__s_waktu['.$this->input->post('waktu',TRUE).']');
            $this->_rules();
            if ($this->form_validation->run()) {
                $insert = array(
																'nama_service' => $this->input->post('nama_service',TRUE),
																'jarak_tempuh' => $this->input->post('jarak_tempuh',TRUE),
                                's_jarak_tempuh' => $this->input->post('s_jarak_tempuh',TRUE),
																'waktu' => $this->input->post('waktu',TRUE),
                                's_waktu' => $this->input->post('s_waktu',TRUE),
															);

                $this->model->get_insert('tb_service',$insert);
                $id_service = $this->db->insert_id();

                $j_perbaikan =  $this->input->post('perbaikan');

                foreach ($j_perbaikan as $jp) {
                    $insert_trans = array('id_service' => $id_service,
                                          'id_perbaikan'=> $jp
                                          );
                    $this->model->get_insert('trans_service',$insert_trans);
                }


                $json['alert']   = 'Berhasil Menyimpan!';
                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      $this->layouts->set_title('Data Service');
      $data = array('layout_title' => 'Data Service',
                      'button'=>'tambah',
                      'aksi' =>site_url(config_item("cpanel").'service/tambah/aksi'),
											'id_service' => set_value('id_service'),
											'nama_service' => set_value('nama_service'),
											'jarak_tempuh' => set_value('jarak_tempuh'),
                      's_jarak_tempuh' => set_value('s_jarak_tempuh'),
											'waktu' => set_value('waktu'),
                      's_waktu' => set_value('s_waktu'),
											);
			 $this->layouts->view(config_item("cpanel").'content/service/form',array(),$data);
  //MODAL TAMBAH
  //$this->layouts->view(config_item("cpanel").'content/service/form',array(),$data,false);
     }
  }

 function edit($id,$status=''){
      if ($status=='aksi') {
          $json = array('success'=>false ,'alert'=>array());
          if ($this->input->is_ajax_request()) {
            $this->form_validation->set_rules('s_jarak_tempuh', 'sampai jarak tempuh', 'trim|xss_clean|required|numeric|callback__s_jarak['.$this->input->post('jarak_tempuh',TRUE).']');
            $this->form_validation->set_rules('s_waktu', 'sampai waktu', 'trim|xss_clean|required|numeric|callback__s_waktu['.$this->input->post('waktu',TRUE).']');
              $this->_rules();
              if ($this->form_validation->run()) {

                $delete = $this->model->get_delete('trans_service',array('id_service'=>$id));
                if (!$delete) {
                  $json['alert'] = '<div id="alert" class="alert alert-danger">Gagal Mengedit jenis perbaikan, karna data terpakai di table lain!<div>';
                }else {
                  $update = array(
                                'nama_service' => $this->input->post('nama_service',TRUE),
                                'jarak_tempuh' => $this->input->post('jarak_tempuh',TRUE),
                                's_jarak_tempuh' => $this->input->post('s_jarak_tempuh',TRUE),
                                'waktu' => $this->input->post('waktu',TRUE),
                                's_waktu' => $this->input->post('s_waktu',TRUE),
                              );
                $this->model->get_update($id,$update);

                  $j_perbaikan =  $this->input->post('perbaikan');

                  foreach ($j_perbaikan as $jp) {
                      $insert_trans = array('id_service' => $id,
                                            'id_perbaikan'=> $jp
                                            );
                      $this->model->get_insert('trans_service',$insert_trans);
                  }
                  $json['alert'] = '<div id="alert" class="alert alert-success">Berhasil Megedit!<div>';
                }

                $json['success'] = true;
            }else{
                foreach ($_POST as $key => $value) {
                  $json['alert'][$key] = form_error($key);
                }
            }
            echo json_encode($json);
        }
    }else{
      if($row=$this->model->get_where($id)){
        $this->layouts->set_title('Data Service');
        $data = array('layout_title' => 'Data Service',
                      'button'=>'edit',
                      'aksi' =>site_url(config_item("cpanel").'service/edit/'.$id.'/aksi'),
											'id_service' => set_value('id_service', $row->id_service),
											'nama_service' => set_value('nama_service', $row->nama_service),
											'jarak_tempuh' => set_value('jarak_tempuh', $row->jarak_tempuh),
                      's_jarak_tempuh' => set_value('s_jarak_tempuh', $row->s_jarak_tempuh),
											'waktu' => set_value('waktu', $row->waktu),
                      's_waktu' => set_value('waktu', $row->s_waktu),
											);
			 $this->layouts->view(config_item("cpanel").'content/service/form',array(),$data);
      //MODAL EDIT
      //$this->layouts->view(config_item("cpanel").'content/service/form',array(),$data,false);
			}else{
      $this->error_404();
    }
  }
}

 function hapus($id){
  if ($this->input->is_ajax_request()) {
    if ($this->model->get_delete('tb_service',array('id_service'=>$id))==false) {
      $data['alert'] = '<div id="alert" class="alert alert-danger">Gagal Menghapus, data ini terpakai di table lain!<div>';
    }else {
      $data['alert'] = '<div id="alert" class="alert alert-success">Berhasil Menghapus!<div>';
    }
      echo json_encode($data);
    }
}

function _s_jarak($str, $jarak)
{
  if ($jarak > $str) {
    $this->form_validation->set_message('_s_jarak', 'field harus di atas jarak tempuh');
    return FALSE;
  }else {
    return TRUE;
  }
}

function _s_waktu($str, $waktu)
{
  if ($waktu > $str) {
    $this->form_validation->set_message('_s_waktu', 'field harus di atas waktu tempuh');
    return FALSE;
  }else {
    return TRUE;
  }
}

}
/* End Controller */
